### PR TITLE
Add optional path specification to libssh.h, and instruction to use brew (for Mac)

### PR DESCRIPTION
**Pull request by guoquan**
Hence Mac is supported

### CODE REVIEW

**Comment by ericcurtin** [comment]
Apple silicon support next? Hopefully it will just work :smile:

**Comment by studgeek** [comment]
It looks like this was approved, but not merged?

**Comment by ericcurtin** [comment]
I actually just got a M1 Mac Mini for some aarch64 work I'm doing, might give this branch a whirl to see if it's still working today.

**Comment by wongjustin99** [comment]
Location is slightly different for me on an M1 using the same brew package. 

`LIBSSH_INCLUDE2 = /opt/homebrew/Cellar/libssh/0.9.6/include/libssh/libssh.h`

Still working through it though, the includes in src/sshping.cos are not picking up the updated header path it seems.

**Comment by wongjustin99** [comment]
Using https://github.com/spook/sshping/pull/27, I was able to get running as well.

**Comment by code-ape** [comment]
Just tried this after merge and still having issues. I'm on an M1 MacBook Pro running the following, any suggestions?

```bash
brew install libssh
make -e LIBSSH_INCLUDE=/opt/homebrew/Cellar/libssh/0.10.4/include/libssh/libssh.h
```

**Comment by hologerry** [comment]
> Just tried this after merge and still having issues. I'm on an M1 MacBook Pro running the following, any suggestions?
> 
> ```shell
> brew install libssh
> make -e LIBSSH_INCLUDE=/opt/homebrew/Cellar/libssh/0.10.4/include/libssh/libssh.h
> ```
> 
> Output is:
> 
> ```
> g++ -Wall -I ext/ -o bin/sshping src/sshping.cxx -lssh
> src/sshping.cxx:38:10: fatal error: 'libssh/libssh.h' file not found
> #include <libssh/libssh.h>
>          ^~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [bin/sshping] Error 1
> ```

For future users:
change the `CMakeLists.txt` according to: #27
And do the following
```
mkdir build
cd build
cmake ..
make
# sudo make install
```

**Comment by guoquan** [comment]
For Mac users with issue locating `libssh.h`, please also consult #23 

It may be good if someone can propose a PR with `$(CFLAGS)` ready and compile instruction in `README.md`

**Pull request merged**
