### PR TITLE
Add option -P, --ping-summary

### PR DESCRIPTION
**Pull request by akobel**
Reports a ping-like summary for the rtts, in the format

  `rtt min/avg/max/mdev = 1.371/2.095/2.505/0.389 ms`

Useful for replacing ping by sshping inside applications that parse the output of ping's rtt line (notably, BackupPC, where ping output is inspected to determine whether a client is reachable via a reasonable connection).

### CODE REVIEW

**Comment by spook** [comment]
@akobel Great idea.  Sorry, I didn't notice this until just now, when I pushed up another PR.  Lemme get thru that other PR then I'll review yours.

**Comment by spook** [comment]
@akobel The README.md has a snapshot of the usage help, please add your -P --ping-summary option to that file too (so it looks like what you'd get from `sshping --help`)

**Comment by akobel** [comment]
@spook Thanks for reviewing. I added the help line in README.md as you suggested.

**Comment by akobel** [comment]
Now also in the man page.
I also tweaked the Makefile slightly. pod2man is not necessarily installed in /usr/bin; e.g., on Arch, it's in /usr/bin/core_perl, and the Make rule didn't allow that. No functional change here.

**Comment by spook** [comment]
@akobel Excellent, thanx.  My last PR caused a couple merge conflicts, working on them.

**Pull request merged**
